name: CI Tests
on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - 'master'

jobs:
  build:
    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - 8.1

    services:
      postgres:
        image: postgres:13.6
        env:
          POSTGRES_DB: yii2-history-tests
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: imagick, pdo_pgsql, opcache
          ini-values: opcache.enable=1, opcache.enable_cli=1, apc.enable_cli=1
        env:
          COMPOSER_TOKEN: ${{ secrets.COMPOSER_GITHUB_TOKEN }}

      - name: Check php and composer
        run: php -v && composer --version

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
            echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
                ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install

      - name: Prepare test
        run: cp tests/.env.sample tests/.env

      - name: Run tests
        run: vendor/bin/codecept run
        env:
          COMPOSER_TOKEN: ${{ secrets.COMPOSER_GITHUB_TOKEN }}

      - name: phpstan static analysis
        uses: php-actions/phpstan@v3
        with:
            path: src/
            configuration: src/phpstan.neon
            memory_limit: 256M